version: '3.8'

services:
  # PostgreSQL veritabanı
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI uygulaması
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/restaurant_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        python app/db/init_db.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  # Frontend için basit HTTP server
  frontend:
    image: python:3.8-slim
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    working_dir: /app
    command: python -m http.server 9000

volumes:
  postgres_data:
